name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout репозитория
      uses: actions/checkout@v4

    - name: Устанавливаем SSH-ключ
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "${{ secrets.EC2_SSH_KEY }}"
        ssh-keyscan -H ubuntu@3.70.234.196 >> ~/.ssh/known_hosts

    - name: Деплой кода на EC2
      run: |
        ssh eubuntu@3.70.234.196 << 'EOF'
          cd /var/www/html/backend
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart myapp
        EOF
